### ISSUE TITLE
Loss is not decreased

### ISSUE THREAD

**Issue by xueyouluo** [carpedm20/word2vec-tensorflow#3]
Does anyone try this code? I ran for a while, the loss is still around 1.78

**Comment by shatu** [comment]
Could be because of the fact that there is no batching in this code, and gradients are propagated per example.

**Comment by carpedm20** [comment]
This is one of the very first project of mine and I recommend you not to use this

**Comment by MiguelAngelRG** [comment]
Hi, I am trying to execute this code and apparently it has some issues. 
For instance, I am having this problem:
https://github.com/carpedm20/word2vec-tensorflow/blob/master/model.py#L98

word_prob += math.pow(self.counter[word_idx][1], self.alpha) / total_count_pow
IndexError: list index out of range

The problem is that the index word_ids is out of range. Has someone fixed the problem? 
In order to run the code, what I have done is just to check if the word_idx is greater than
the site of the array, but I do not know if this change is affecting the final embeddings. 
Has anyone taken a look through this?

Thank you in advance.
